In [1]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_vector=[one_hot(words,voc_size) for words in sent]
one_hot_vector

[[102, 8152, 2991, 7250],
 [102, 8152, 2991, 1504],
 [102, 9449, 2991, 8002],
 [6250, 9603, 3437, 9620, 3360],
 [6250, 9603, 3437, 9620, 147],
 [2763, 102, 6465, 2991, 348],
 [327, 8253, 3213, 9620]]

In [6]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_vector,padding = 'pre',maxlen = sent_length)
print(embedded_doc)

[[   0    0    0    0  102 8152 2991 7250]
 [   0    0    0    0  102 8152 2991 1504]
 [   0    0    0    0  102 9449 2991 8002]
 [   0    0    0 6250 9603 3437 9620 3360]
 [   0    0    0 6250 9603 3437 9620  147]
 [   0    0    0 2763  102 6465 2991  348]
 [   0    0    0    0  327 8253 3213 9620]]


In [7]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([[[ 0.0237501 ,  0.0054374 ,  0.03226105, -0.01803731,
         -0.00294556,  0.04229707, -0.03969689,  0.04531987,
         -0.01820079,  0.01085941],
        [ 0.0237501 ,  0.0054374 ,  0.03226105, -0.01803731,
         -0.00294556,  0.04229707, -0.03969689,  0.04531987,
         -0.01820079,  0.01085941],
        [ 0.0237501 ,  0.0054374 ,  0.03226105, -0.01803731,
         -0.00294556,  0.04229707, -0.03969689,  0.04531987,
         -0.01820079,  0.01085941],
        [ 0.0237501 ,  0.0054374 ,  0.03226105, -0.01803731,
         -0.00294556,  0.04229707, -0.03969689,  0.04531987,
         -0.01820079,  0.01085941],
        [-0.00470733,  0.03767088, -0.03994939,  0.00560709,
         -0.01460854,  0.04480929,  0.00984685, -0.04899088,
         -0.00635514,  0.01441752],
        [ 0.04035221, -0.04611423,  0.02799424,  0.04273501,
          0.02822523, -0.04933902, -0.02592958, -0.03309713,
         -0.03929269,  0.00167159],
        [ 0.02298078,  0.02869296, -0.04800317, -0.0